# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billjobs', '0008_auto_20180308_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2018, unique=True)),
                ('january', models.FloatField(default=0.0)),
                ('february', models.FloatField(default=0.0)),
                ('march', models.FloatField(default=0.0)),
                ('april', models.FloatField(default=0.0)),
                ('may', models.FloatField(default=0.0)),
                ('june', models.FloatField(default=0.0)),
                ('july', models.FloatField(default=0.0)),
                ('august', models.FloatField(default=0.0)),
                ('september', models.FloatField(default=0.0)),
                ('october', models.FloatField(default=0.0)),
                ('november', models.FloatField(default=0.0)),
                ('december', models.FloatField(default=0.0)),
            ],
        ),
    ]
