# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billjobs', '0011_auto_20180507_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(max_length=20),
        ),
    ]
