language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py test
