language: python
python:
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - python manage.py makemigrations
  - coverage run --source="." manage.py test billjobs
